api:
    resource: '.'
    type:     'api_platform'
    prefix:   /api

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

app_controller:
    resource: '@AppBundle/Controller/'
    type:     'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
